# Generated by Django 3.1.1 on 2020-09-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200921_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='picture',
            new_name='image',
        ),
    ]
