# Generated by Django 3.1.1 on 2020-09-21 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200921_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='hours',
        ),
        migrations.AddField(
            model_name='locationhours',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
    ]
