# Generated by Django 3.1.1 on 2020-09-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200921_0434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationhours',
            options={'verbose_name': 'Location Hours', 'verbose_name_plural': 'Location Hours'},
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='TX', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.IntegerField(default=76244, max_length=5),
            preserve_default=False,
        ),
    ]
