# Generated by Django 3.1.1 on 2020-09-21 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20200921_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='locationhours',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='locations.location'),
        ),
    ]
