# Generated by Django 3.1.1 on 2020-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodcategory_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='order_index',
            field=models.IntegerField(null=True),
        ),
    ]
