# Generated by Django 3.1.1 on 2020-11-02 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_fooditem_order_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('listed', models.BooleanField()),
                ('order_index', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Drink Category',
                'verbose_name_plural': 'Drink Categories',
            },
        ),
        migrations.CreateModel(
            name='DrinkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food.drinkcategory')),
            ],
            options={
                'verbose_name': 'Drink Item',
                'verbose_name_plural': 'Drink Items',
            },
        ),
    ]
