# Generated by Django 3.1.1 on 2020-11-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_drinkcategory_drinkitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkitem',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
